export const dbArray = [
  {
    id: 0,
    name: "Max Mustermann",
    address: "Breite Str. 30-36, 10178 Berlin",
    email: "max@mustermail.de",
    phone: "+49800 3301000",
    website: "https://de.wikipedia.org/wiki/Mustermann",
    image: "images/db_images/austin-wade-X6Uj51n5CE8-unsplash.jpg",
  },
  {
    id: 1,
    name: "Erika Musterfrau",
    address: "Am Kanal 47, 14467 Potsdam",
    email: "erika@mustermail.de",
    phone: "+49800 3301000",
    website: "https://de.wikipedia.org/wiki/Mustermann",
    image: "images/db_images/christopher-campbell-rDEOVtE7vOs-unsplash.jpg",
  },
  {
    id: 2,
    name: "John Doe",
    address: "476 5th Ave, New York, NY 10018, Vereinigte Staaten",
    email: "john@doesmail.com",
    phone: "+49800 3301000",
    website: "https://de.wikipedia.org/wiki/John_Doe",
    image: "images/db_images/robert-godwin-cdksyTqEXzo-unsplash.jpg",
  },
  {
    id: 3,
    name: "Jane Roe",
    address: "900 Wesley Pl SW, Washington, DC 20024, Vereinigte Staaten",
    email: "jane@roesmail.com",
    phone: "+49800 3301000",
    website: "https://de.wikipedia.org/wiki/John_Doe",
    image: "images/db_images/jake-nackos-IF9TK5Uy-KI-unsplash.jpg",
  },
];
